### ISSUE TITLE
高并发下请求数据问题

### ISSUE THREAD

**Issue by mrurl** [a07061625/swooleyaf#1]
学习下代码，关闭协程后获取请求参数从$_GET 和 $_POST中的，返回响应后清空数据，这种在并发下可能会出现后面的请求把前一个请求的参数覆盖吗？用simple request或者自己写个请求类传给dispatcher这种会好点吧？

**Comment by a07061625** [comment]
不会的，因为每次请求进来是在一个ｗｏｒｋｅｒ进程中处理的，在一个请求没有处理完成的情况下，是不会继续接收请求数据的

**Comment by a07061625** [comment]
> 学习下代码，关闭协程后获取请求参数从$_GET 和 $_POST中的，返回响应后清空数据，这种在并发下可能会出现后面的请求把前一个请求的参数覆盖吗？用simple request或者自己写个请求类传给dispatcher这种会好点吧？

ｙａｆ的实例是在ｗｏｒｋｅｒ进程中，每个ｗｏｒｋｅｒ进程一次只处理一个请求，处理完成以后才会接收下一个请求，不会出现你说的覆盖现象

**Comment by mrurl** [comment]
这样在worker中就是同步的，开启协程后一个worker才能同时处理多个请求
